CREATE TABLE BE_USER 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(100) NOT NULL 
, SURNAME VARCHAR2(100) NOT NULL 
, USERNAME VARCHAR2(50) NOT NULL 
, PASSWD VARCHAR2(300) NOT NULL 
, ABOUT VARCHAR2(4000) 
, FACEBOOK_PROFILE VARCHAR2(300) 
, CONSTRAINT BE_USER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE BE_USER
ADD CONSTRAINT BE_USER_USERNAME_UK UNIQUE 
(
  USERNAME 
)
ENABLE;

COMMENT ON COLUMN BE_USER.ID IS 'unique  user id';

COMMENT ON COLUMN BE_USER.NAME IS 'user''s name';

COMMENT ON COLUMN BE_USER.SURNAME IS 'users\ surname';

COMMENT ON COLUMN BE_USER.USERNAME IS 'unique user name';

COMMENT ON COLUMN BE_USER.PASSWD IS 'MD5 hash value of user password';

COMMENT ON COLUMN BE_USER.ABOUT IS 'user info';

COMMENT ON COLUMN BE_USER.FACEBOOK_PROFILE IS 'HTTP link of user''s facebook profile';
